import { CLEANING_IMAGES } from "../cleaningServicesList";
import type { CleaningServiceConfig } from "../types";
import { cleaningPageContent, cleaningSidebarContent, step } from "./shared";

// /services/home-cleaning
export const homeCleaningConfig: CleaningServiceConfig = {
  slug: "home-cleaning",
  group: "home",
  pageContent: cleaningPageContent({
    slug: "home-cleaning",
    serviceName: "Home Cleaning",
    image: CLEANING_IMAGES.home,
    heroEyebrow: "Full-home Deep Cleaning",
    heroDescription: "Ceiling fans to floor grouting — a trained crew deep-cleans every room and restores your home's shine.",
    heroFeatures: [
      { title: "Trained", subtitle: "Crew" },
      { title: "Machine", subtitle: "Scrubbing" },
      { title: "Safe", subtitle: "Chemicals" },
      { title: "Transparent", subtitle: "Pricing" },
    ],
    walkthroughEyebrow: "Complete Home Cleaning",
    walkthroughTitle: "How Home Cleaning Works",
    walkthroughDescription: "A room-by-room deep clean by a trained crew with machines and professional-grade products.",
    steps: [
      step(1, "Book Your Cleaning", "Tell us your property type and furnishing, then pick a convenient slot."),
      step(2, "Crew Assigned", "A background-verified cleaning crew arrives with machines, tools and products."),
      step(3, "Room-by-room Clean", "Dusting, fans and fixtures, floor scrubbing, kitchen and bathroom degreasing."),
      step(4, "Final Walkthrough", "We check every room with you before leaving, so nothing is missed."),
    ],
    statsTitle: "TRUSTED FOR SPARKLING HOMES",
    statsHighlight: "SPARKLING HOMES",
    stats: [
      { value: "3K+", label: "Homes Cleaned" },
      { value: "4-6 Hrs", label: "Per Home" },
      { value: "2-4", label: "Crew Members" },
      { value: "4.8", label: "Average Rating" },
    ],
    bannerEyebrow: "Home Cleaning",
    bannerTitle: "Move-in Shine, Every Room",
    bannerHighlight: "Every Room",
    bannerDescription: "Deep cleaning for move-ins, move-outs, festivals or just because — done in a day.",
    areasDescription: "Doorstep home deep cleaning for flats, villas and offices across Ghaziabad.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Home Cleaning",
    ["Trained, background-verified crew", "Machines and professional products", "Kitchen and bathroom degreasing", "Final walkthrough with you"],
    [
      { q: "How long does a full-home clean take?", a: "About 4–6 hours for a 2–3 BHK, depending on furnishing and how dirty it is." },
      { q: "Do I need to provide anything?", a: "Only water and electricity. The crew brings all machines, tools and cleaning products." },
      { q: "Are the chemicals safe?", a: "Yes, we use professional-grade products that are safe for kids and pets once dry." },
      { q: "Do you clean empty flats for move-in?", a: "Yes — select Move-in / Move-out and Unfurnished in the booking form." },
    ]
  ),
  form: {
    formId: "home-cleaning-details-form",
    stepTitle: "Home Cleaning Details",
    stepSubtitle: "Tell us about your home so we send the right crew size",
    typeLabel: "Property Type",
    typeOptions: ["1 BHK", "2 BHK", "3 BHK", "4 BHK+", "Villa", "Office"],
    sizeLabel: "Furnishing",
    sizeOptions: ["Unfurnished", "Semi-furnished", "Fully Furnished"],
    issueLabel: "What kind of cleaning do you need?",
    issues: [
      { id: "deep", label: "Full-home Deep Clean", icon: "house" },
      { id: "move", label: "Move-in / Move-out", icon: "truck" },
      { id: "renovation", label: "Post-renovation", icon: "hammer" },
      { id: "festival", label: "Pre-festival Cleaning", icon: "party" },
      { id: "maintenance", label: "General Maintenance", icon: "brush" },
      { id: "others", label: "Others", icon: "sparkles" },
    ],
    defaultIssueId: "deep",
    descriptionPlaceholder: "E.g. 3 BHK semi-furnished flat, move-in cleaning before shifting.",
    photoHint: "Upload photos of the rooms",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Living Rooms", "Bedrooms", "Kitchens", "Bathrooms", "Balconies", "Ceiling Fans", "Windows", "Floors", "Wardrobes (outside)", "Switchboards"],
  showcaseIcon: "house",
};

// /services/kitchen-cleaning
export const kitchenCleaningConfig: CleaningServiceConfig = {
  slug: "kitchen-cleaning",
  group: "home",
  pageContent: cleaningPageContent({
    slug: "kitchen-cleaning",
    serviceName: "Kitchen Cleaning",
    image: CLEANING_IMAGES.kitchen,
    heroEyebrow: "Deep Kitchen Degreasing",
    heroDescription: "Cabinets, tiles, sink, chimney exterior and appliances — professionally degreased with food-safe products.",
    heroFeatures: [
      { title: "Heavy Grease", subtitle: "Removal" },
      { title: "Food-safe", subtitle: "Products" },
      { title: "Cabinet", subtitle: "Cleaning" },
      { title: "Same Day", subtitle: "Service" },
    ],
    walkthroughEyebrow: "Complete Kitchen Cleaning",
    walkthroughTitle: "How Kitchen Cleaning Works",
    walkthroughDescription: "Degreasers that cut through oil build-up, followed by a food-safe rinse on every surface.",
    steps: [
      step(1, "Book Your Cleaning", "Tell us the kitchen type and size, then choose a convenient slot."),
      step(2, "Expert Assigned", "A trained cleaner arrives with degreasers, scrubbers and food-safe products."),
      step(3, "Degrease Everything", "Tiles, slab, cabinets inside and out, sink, taps and appliance exteriors."),
      step(4, "Food-safe Finish", "Surfaces are rinsed and wiped down so the kitchen is ready to cook in."),
    ],
    statsTitle: "TRUSTED FOR GREASE-FREE KITCHENS",
    statsHighlight: "GREASE-FREE KITCHENS",
    stats: [
      { value: "4K+", label: "Kitchens Cleaned" },
      { value: "3-4 Hrs", label: "Per Kitchen" },
      { value: "100%", label: "Food-safe Products" },
      { value: "4.8", label: "Average Rating" },
    ],
    bannerEyebrow: "Kitchen Cleaning",
    bannerTitle: "A Kitchen You'll Love Cooking In",
    bannerHighlight: "Love Cooking In",
    bannerDescription: "Months of oil and grime removed from tiles, cabinets and fittings in a single visit.",
    areasDescription: "Doorstep kitchen deep cleaning across major Ghaziabad neighbourhoods.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Kitchen Cleaning",
    ["Cuts through heavy grease", "Food-safe cleaning products", "Cabinets cleaned inside and out", "Appliance exteriors included"],
    [
      { q: "Do you clean inside the cabinets?", a: "Yes, if they are emptied before the visit. Select Cabinet Interiors in the form." },
      { q: "Is the chimney cleaned too?", a: "The chimney exterior is included. Filter and motor servicing is a separate Chimney Repair service." },
      { q: "Are the products safe around food?", a: "Yes, surfaces are finished with food-safe products and wiped down before we leave." },
      { q: "How long does it take?", a: "About 3–4 hours for most kitchens, longer for heavy grease or large modular kitchens." },
    ]
  ),
  form: {
    formId: "kitchen-cleaning-details-form",
    stepTitle: "Kitchen Cleaning Details",
    stepSubtitle: "Tell us about your kitchen so we bring the right degreasers",
    typeLabel: "Kitchen Type",
    typeOptions: ["Modular", "Non-modular", "Open Kitchen"],
    sizeLabel: "Kitchen Size",
    sizeOptions: ["Small", "Medium", "Large"],
    issueLabel: "What does the kitchen need?",
    issues: [
      { id: "grease", label: "Heavy Grease", icon: "flame" },
      { id: "chimney", label: "Chimney Exterior", icon: "wind" },
      { id: "cabinets", label: "Cabinet Interiors", icon: "layers" },
      { id: "sink", label: "Sink & Tap Descaling", icon: "droplets" },
      { id: "tiles", label: "Backsplash Tiles", icon: "grid" },
      { id: "others", label: "Others", icon: "kitchen" },
    ],
    defaultIssueId: "grease",
    descriptionPlaceholder: "E.g. Modular kitchen with heavy grease on tiles and cabinets.",
    photoHint: "Upload photos of the kitchen",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Wall Tiles", "Kitchen Slab", "Cabinets", "Sink & Taps", "Chimney Exterior", "Hob & Stove", "Fridge Exterior", "Microwave Exterior", "Exhaust Fan", "Kitchen Floor"],
  showcaseIcon: "kitchen",
};

// /services/bathroom-cleaning
export const bathroomCleaningConfig: CleaningServiceConfig = {
  slug: "bathroom-cleaning",
  group: "home",
  pageContent: cleaningPageContent({
    slug: "bathroom-cleaning",
    serviceName: "Bathroom Cleaning",
    image: CLEANING_IMAGES.bathroom,
    heroEyebrow: "Descaling & Sanitisation",
    heroDescription: "Tile, grout and fittings descaled, scrubbed and disinfected — hotel-grade clean bathrooms.",
    heroFeatures: [
      { title: "Hard Water", subtitle: "Descaling" },
      { title: "Grout", subtitle: "Scrubbing" },
      { title: "Full", subtitle: "Disinfection" },
      { title: "Same Day", subtitle: "Service" },
    ],
    walkthroughEyebrow: "Complete Bathroom Cleaning",
    walkthroughTitle: "How Bathroom Cleaning Works",
    walkthroughDescription: "Descaling and machine scrubbing that removes what regular cleaning leaves behind.",
    steps: [
      step(1, "Book Your Cleaning", "Tell us the bathroom type and how many, then pick a convenient slot."),
      step(2, "Expert Assigned", "A trained cleaner arrives with descalers, scrubbing machines and disinfectants."),
      step(3, "Descale & Scrub", "Tiles, grout, WC, basin, taps and shower fittings descaled and machine-scrubbed."),
      step(4, "Sanitise & Shine", "A full disinfection spray and fitting polish for a hotel-grade finish."),
    ],
    statsTitle: "TRUSTED FOR HYGIENIC BATHROOMS",
    statsHighlight: "HYGIENIC BATHROOMS",
    stats: [
      { value: "6K+", label: "Bathrooms Cleaned" },
      { value: "60 Min", label: "Per Bathroom" },
      { value: "99.9%", label: "Germs Removed" },
      { value: "4.8", label: "Average Rating" },
    ],
    bannerEyebrow: "Bathroom Cleaning",
    bannerTitle: "Hotel-grade Clean, At Home",
    bannerHighlight: "At Home",
    bannerDescription: "Hard water stains, black grout and dull fittings — descaled and disinfected in one visit.",
    areasDescription: "Doorstep bathroom deep cleaning across major Ghaziabad neighbourhoods.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Bathroom Cleaning",
    ["Removes hard water stains", "Machine scrubbing of grout", "Full disinfection spray", "Fittings descaled and polished"],
    [
      { q: "Will hard water stains come off?", a: "Most do. Very old etching on glass or tiles may only lighten — we tell you before starting." },
      { q: "Can black grout be cleaned?", a: "Yes, machine scrubbing removes most grout blackening. Damaged grout needs re-grouting, which is separate." },
      { q: "Are the chemicals safe?", a: "Yes, we use professional descalers and disinfectants that are safe once the bathroom is rinsed." },
      { q: "How long does it take?", a: "Around 60–90 minutes per bathroom." },
    ]
  ),
  form: {
    formId: "bathroom-cleaning-details-form",
    stepTitle: "Bathroom Cleaning Details",
    stepSubtitle: "Tell us about the bathrooms so we plan the visit",
    typeLabel: "Bathroom Type",
    typeOptions: ["Indian", "Western", "With Bathtub"],
    sizeLabel: "Number of Bathrooms",
    sizeOptions: ["1", "2", "3", "4+"],
    issueLabel: "What does the bathroom need?",
    issues: [
      { id: "hardwater", label: "Hard Water Stains", icon: "droplets" },
      { id: "grout", label: "Grout Blackening", icon: "grid" },
      { id: "odour", label: "Bad Odour", icon: "wind" },
      { id: "descale", label: "Descaling Fittings", icon: "shower" },
      { id: "sanitise", label: "Full Sanitisation", icon: "spray" },
      { id: "others", label: "Others", icon: "bath" },
    ],
    defaultIssueId: "hardwater",
    descriptionPlaceholder: "E.g. Two bathrooms with hard water stains on tiles and taps.",
    photoHint: "Upload photos of the bathroom",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Wall Tiles", "Floor Grout", "WC / Toilet", "Wash Basin", "Taps & Mixers", "Shower Panels", "Bathtubs", "Mirrors", "Glass Partitions", "Exhaust Fans"],
  showcaseIcon: "bath",
};
