import { CLEANING_IMAGES } from "../cleaningServicesList";
import type { CleaningServiceConfig } from "../types";
import { cleaningPageContent, cleaningSidebarContent, step } from "./shared";

const SEATS = ["1 - 3 Seats", "4 - 5 Seats", "6 - 7 Seats", "8+ Seats"];

// /services/sofa-shampooing
export const sofaShampooingConfig: CleaningServiceConfig = {
  slug: "sofa-shampooing",
  group: "sofa",
  pageContent: cleaningPageContent({
    slug: "sofa-shampooing",
    serviceName: "Sofa Shampooing",
    image: CLEANING_IMAGES.sofaShampooing,
    heroEyebrow: "Professional Sofa Deep Cleaning",
    heroDescription: "Foam extraction cleaning for fabric sofas — stains, dust mites and odours gone, like new again.",
    heroFeatures: [
      { title: "Foam", subtitle: "Extraction" },
      { title: "Stain", subtitle: "Treatment" },
      { title: "Fabric", subtitle: "Safe" },
      { title: "Same Day", subtitle: "Service" },
    ],
    walkthroughEyebrow: "Deep Sofa Cleaning",
    walkthroughTitle: "How Sofa Shampooing Works",
    walkthroughDescription: "Shampoo, scrub and hot-water extraction that pulls dirt out of every fibre, not just the surface.",
    steps: [
      step(1, "Book Your Cleaning", "Tell us your sofa material and number of seats, then pick a convenient slot."),
      step(2, "Expert Assigned", "A trained cleaning professional arrives with foam shampoo and an extraction machine."),
      step(3, "Shampoo & Extraction", "Vacuuming, stain pre-treatment, foam shampoo and hot-water extraction of the dirt."),
      step(4, "Dry & Fresh", "A deodoriser finish leaves the sofa fresh — ready to use in 4–6 hours."),
    ],
    statsTitle: "TRUSTED FOR SPOTLESS SOFAS",
    statsHighlight: "SPOTLESS SOFAS",
    stats: [
      { value: "5K+", label: "Sofas Cleaned" },
      { value: "60 Min", label: "Average Job Time" },
      { value: "100%", label: "Fabric-safe Products" },
      { value: "4.8", label: "Average Rating" },
    ],
    bannerEyebrow: "Sofa Shampooing",
    bannerTitle: "Your Sofa, Like New Again",
    bannerHighlight: "Like New Again",
    bannerDescription: "Deep foam cleaning that lifts stains, sweat and pet odour from fabric sofas — right in your living room.",
    areasDescription: "Doorstep sofa shampooing for homes and offices across major Ghaziabad neighbourhoods.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Sofa Shampooing",
    ["Hot-water extraction, not just a wipe", "Stain and odour pre-treatment", "Fabric-safe, child-safe shampoo", "Trained, background-verified crew"],
    [
      { q: "How long does the sofa take to dry?", a: "Usually 4–6 hours with a fan on. We extract most of the water so it isn't left soaked." },
      { q: "Will all stains come out?", a: "Most food, tea and dirt stains do. Very old ink or dye stains may only lighten — we tell you before starting." },
      { q: "Is it safe for kids and pets?", a: "Yes, we use mild, fabric-safe shampoo and finish with a non-toxic deodoriser." },
      { q: "Do you clean leather sofas?", a: "Leather gets a separate conditioner-based clean. Select Leather in the booking form." },
    ]
  ),
  form: {
    formId: "sofa-shampooing-details-form",
    stepTitle: "Sofa Cleaning Details",
    stepSubtitle: "Tell us about your sofa so we bring the right shampoo and machine",
    typeLabel: "Sofa Material",
    typeOptions: ["Fabric", "Leather", "Suede / Velvet", "Rexine"],
    sizeLabel: "Number of Seats",
    sizeOptions: SEATS,
    issueLabel: "What does the sofa need?",
    issues: [
      { id: "stains", label: "Deep Stains", icon: "droplets" },
      { id: "odour", label: "Bad Odour", icon: "wind" },
      { id: "dust", label: "General Dust & Grime", icon: "brush" },
      { id: "party", label: "Post-party Cleanup", icon: "party" },
      { id: "pet", label: "Pet Hair & Odour", icon: "pet" },
      { id: "others", label: "Others", icon: "sparkles" },
    ],
    defaultIssueId: "stains",
    descriptionPlaceholder: "E.g. 5-seater fabric sofa with tea stains on two cushions.",
    photoHint: "Upload photos of the stains",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Fabric Sofas", "L-shaped Sofas", "Recliners", "Sofa Cum Beds", "Dining Chairs", "Office Chairs", "Cushions", "Ottomans", "Puffies", "Headboards"],
  showcaseIcon: "sofa",
};

// /services/sofa-dry-cleaning
export const sofaDryCleaningConfig: CleaningServiceConfig = {
  slug: "sofa-dry-cleaning",
  group: "sofa",
  pageContent: cleaningPageContent({
    slug: "sofa-dry-cleaning",
    serviceName: "Sofa Dry Cleaning",
    image: CLEANING_IMAGES.sofaDryCleaning,
    heroEyebrow: "Water-free Sofa Cleaning",
    heroDescription: "Solvent-based dry cleaning for suede, velvet and delicate fabrics — dries in minutes, no water damage.",
    heroFeatures: [
      { title: "Zero", subtitle: "Water" },
      { title: "Delicate", subtitle: "Fabric Safe" },
      { title: "Ready", subtitle: "In Minutes" },
      { title: "Same Day", subtitle: "Service" },
    ],
    walkthroughEyebrow: "Gentle Dry Cleaning",
    walkthroughTitle: "How Sofa Dry Cleaning Works",
    walkthroughDescription: "A dry solvent lifts dirt from fabrics that can't take water, so your sofa is usable almost immediately.",
    steps: [
      step(1, "Book Your Cleaning", "Choose your sofa material and number of seats, then pick a time slot."),
      step(2, "Fabric Check", "Our expert tests the solvent on a hidden patch to make sure the fabric is safe."),
      step(3, "Dry Solvent Clean", "Vacuuming, spot stain treatment and a dry solvent clean, brushed in by hand."),
      step(4, "Use It Right Away", "No soaking, no waiting — the sofa is ready to sit on in minutes."),
    ],
    statsTitle: "TRUSTED FOR DELICATE FABRICS",
    statsHighlight: "DELICATE FABRICS",
    stats: [
      { value: "2K+", label: "Sofas Dry Cleaned" },
      { value: "0", label: "Litres of Water" },
      { value: "15 Min", label: "Drying Time" },
      { value: "4.8", label: "Average Rating" },
    ],
    bannerEyebrow: "Sofa Dry Cleaning",
    bannerTitle: "Clean Without a Drop of Water",
    bannerHighlight: "Without a Drop of Water",
    bannerDescription: "The safe way to clean velvet, suede and delicate upholstery — no shrinking, no water marks.",
    areasDescription: "Doorstep sofa dry cleaning across major Ghaziabad neighbourhoods.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Sofa Dry Cleaning",
    ["Safe for suede, velvet and silk blends", "No water marks or shrinking", "Ready to use in minutes", "Patch-tested before every clean"],
    [
      { q: "Which sofas need dry cleaning?", a: "Suede, velvet, silk blends and fabrics labelled 'S' (solvent only) should be dry cleaned, not shampooed." },
      { q: "Does dry cleaning remove stains?", a: "Light and fresh stains, yes. Heavy set-in stains on water-safe fabric are better handled by shampooing." },
      { q: "Is there any smell afterwards?", a: "A faint solvent smell fades within an hour with the windows open." },
      { q: "How is it priced?", a: "Per seat. The final price is confirmed by the expert after checking the sofa." },
    ]
  ),
  form: {
    formId: "sofa-dry-cleaning-details-form",
    stepTitle: "Sofa Cleaning Details",
    stepSubtitle: "Tell us about the fabric so we choose the right solvent",
    typeLabel: "Sofa Material",
    typeOptions: ["Suede", "Velvet", "Delicate Fabric", "Leather"],
    sizeLabel: "Number of Seats",
    sizeOptions: SEATS,
    issueLabel: "What does the sofa need?",
    issues: [
      { id: "suede", label: "Suede / Velvet Sofa", icon: "sofa" },
      { id: "delicate", label: "Delicate Fabric", icon: "layers" },
      { id: "refresh", label: "Quick Refresh Needed", icon: "sparkles" },
      { id: "stains", label: "Light Stains", icon: "droplets" },
      { id: "guests", label: "Post-guest Cleaning", icon: "party" },
      { id: "others", label: "Others", icon: "brush" },
    ],
    defaultIssueId: "suede",
    descriptionPlaceholder: "E.g. Velvet 3-seater needs a refresh before guests arrive.",
    photoHint: "Upload photos of the sofa fabric",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Velvet Sofas", "Suede Sofas", "Silk Blends", "Chesterfields", "Recliners", "Accent Chairs", "Cushions", "Headboards", "Ottomans", "Curtains"],
  showcaseIcon: "armchair",
};

// /services/carpet-cleaning
export const carpetCleaningConfig: CleaningServiceConfig = {
  slug: "carpet-cleaning",
  group: "sofa",
  pageContent: cleaningPageContent({
    slug: "carpet-cleaning",
    serviceName: "Carpet Cleaning",
    image: CLEANING_IMAGES.carpet,
    heroEyebrow: "On-site Carpet Deep Cleaning",
    heroDescription: "Rugs and wall-to-wall carpets shampooed and extracted at your home — no dismantling, no transport.",
    heroFeatures: [
      { title: "On-site", subtitle: "Cleaning" },
      { title: "Shampoo", subtitle: "Extraction" },
      { title: "Stain", subtitle: "Treatment" },
      { title: "Transparent", subtitle: "Pricing" },
    ],
    walkthroughEyebrow: "Deep Carpet Cleaning",
    walkthroughTitle: "How Carpet Cleaning Works",
    walkthroughDescription: "Deep shampoo and extraction that reaches the base of the pile, where dust and allergens settle.",
    steps: [
      step(1, "Book Your Cleaning", "Tell us the carpet type and area, then pick a convenient slot."),
      step(2, "Expert Assigned", "A trained cleaner arrives with a carpet shampoo and extraction machine."),
      step(3, "Shampoo & Extract", "Dry vacuuming, stain pre-treatment, shampoo and hot-water extraction."),
      step(4, "Groom & Dry", "The pile is groomed and left to dry — usually within 6–8 hours."),
    ],
    statsTitle: "TRUSTED FOR CLEANER FLOORS",
    statsHighlight: "CLEANER FLOORS",
    stats: [
      { value: "3K+", label: "Carpets Cleaned" },
      { value: "1L+", label: "Sq ft Cleaned" },
      { value: "100%", label: "On-site Service" },
      { value: "4.7", label: "Average Rating" },
    ],
    bannerEyebrow: "Carpet Cleaning",
    bannerTitle: "Fresh Carpets, No Pickup Needed",
    bannerHighlight: "No Pickup Needed",
    bannerDescription: "Rugs, runners and wall-to-wall carpets deep-cleaned where they lie.",
    areasDescription: "Doorstep carpet and rug cleaning for homes and offices across Ghaziabad.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Carpet Cleaning",
    ["Cleaned on-site, no transport", "Hot-water extraction machines", "Safe for handmade rugs", "Priced per square foot"],
    [
      { q: "Do you take the carpet away?", a: "No, everything is done at your home. Wall-to-wall carpets stay in place." },
      { q: "How long does it take to dry?", a: "Around 6–8 hours with a fan on. Avoid walking on it until it's dry." },
      { q: "Can you clean Persian or handmade rugs?", a: "Yes, with a gentler low-moisture process. Select Persian / Handmade in the form." },
      { q: "How is carpet cleaning priced?", a: "Per square foot. The expert measures the carpet and confirms the price before starting." },
    ]
  ),
  form: {
    formId: "carpet-cleaning-details-form",
    stepTitle: "Carpet Cleaning Details",
    stepSubtitle: "Tell us about the carpet so we bring the right equipment",
    typeLabel: "Carpet Type",
    typeOptions: ["Rug", "Wall-to-wall", "Persian / Handmade", "Office Carpet"],
    sizeLabel: "Carpet Area (sq ft)",
    sizeOptions: ["Below 50 sq ft", "50 - 100 sq ft", "100 - 200 sq ft", "Above 200 sq ft"],
    issueLabel: "What does the carpet need?",
    issues: [
      { id: "soiling", label: "Heavy Soiling", icon: "brush" },
      { id: "stains", label: "Wine / Food Stains", icon: "droplets" },
      { id: "pet", label: "Pet Odour", icon: "pet" },
      { id: "dust", label: "Post-renovation Dust", icon: "hammer" },
      { id: "refresh", label: "Rug Refresh", icon: "sparkles" },
      { id: "others", label: "Others", icon: "grid" },
    ],
    defaultIssueId: "soiling",
    descriptionPlaceholder: "E.g. 8x10 ft rug with food stains near the dining area.",
    photoHint: "Upload photos of the carpet",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Area Rugs", "Wall-to-wall Carpets", "Persian Rugs", "Handmade Rugs", "Runners", "Office Carpets", "Door Mats", "Carpet Tiles", "Shag Rugs", "Kids' Play Mats"],
  showcaseIcon: "grid",
};

// /services/mattress-cleaning
export const mattressCleaningConfig: CleaningServiceConfig = {
  slug: "mattress-cleaning",
  group: "sofa",
  pageContent: cleaningPageContent({
    slug: "mattress-cleaning",
    serviceName: "Mattress Cleaning",
    image: CLEANING_IMAGES.mattress,
    heroEyebrow: "Dust-mite & Allergen Removal",
    heroDescription: "UV and extraction cleaning that removes dust mites, sweat and allergens — better sleep, healthier air.",
    heroFeatures: [
      { title: "Dust-mite", subtitle: "Removal" },
      { title: "UV", subtitle: "Treatment" },
      { title: "Anti-allergen", subtitle: "Spray" },
      { title: "Same Day", subtitle: "Service" },
    ],
    walkthroughEyebrow: "Hygienic Mattress Cleaning",
    walkthroughTitle: "How Mattress Cleaning Works",
    walkthroughDescription: "Vacuum, UV and extraction on both sides of the mattress to remove what you can't see.",
    steps: [
      step(1, "Book Your Cleaning", "Tell us the mattress size and how many, then pick a time slot."),
      step(2, "Expert Assigned", "A trained cleaner arrives with a high-suction vacuum, UV lamp and extractor."),
      step(3, "Deep Clean", "HEPA vacuuming, UV treatment, stain spot-cleaning and extraction on both sides."),
      step(4, "Sleep Better", "An anti-allergen spray finishes the job — ready to use in 3–4 hours."),
    ],
    statsTitle: "TRUSTED FOR HEALTHIER SLEEP",
    statsHighlight: "HEALTHIER SLEEP",
    stats: [
      { value: "4K+", label: "Mattresses Cleaned" },
      { value: "99%", label: "Dust Mites Removed" },
      { value: "45 Min", label: "Per Mattress" },
      { value: "4.8", label: "Average Rating" },
    ],
    bannerEyebrow: "Mattress Cleaning",
    bannerTitle: "Sleep on a Cleaner Mattress",
    bannerHighlight: "Cleaner Mattress",
    bannerDescription: "Deep cleaning that removes dust mites, sweat and allergens hiding inside your mattress.",
    areasDescription: "Doorstep mattress cleaning for homes, PGs and hotels across Ghaziabad.",
  }),
  sidebarContent: cleaningSidebarContent(
    "Mattress Cleaning",
    ["UV + extraction on both sides", "Removes dust mites and allergens", "Stain spot-cleaning included", "Anti-allergen finish"],
    [
      { q: "How often should a mattress be cleaned?", a: "Every 6 months, or every 3 months if someone at home has a dust allergy or asthma." },
      { q: "When can we sleep on it?", a: "In about 3–4 hours, once it's fully dry." },
      { q: "Do you clean both sides?", a: "Yes, both sides and the edges are cleaned unless the mattress is single-sided." },
      { q: "Will it remove sweat and urine stains?", a: "Fresh stains, yes. Old stains usually lighten a lot; odour is removed along with them." },
    ]
  ),
  form: {
    formId: "mattress-cleaning-details-form",
    stepTitle: "Mattress Cleaning Details",
    stepSubtitle: "Tell us about the mattresses so we plan the visit",
    typeLabel: "Mattress Size",
    typeOptions: ["Single", "Double", "Queen", "King"],
    sizeLabel: "Number of Mattresses",
    sizeOptions: ["1", "2", "3", "4+"],
    issueLabel: "What does the mattress need?",
    issues: [
      { id: "allergy", label: "Dust Mite Allergy", icon: "health" },
      { id: "sweat", label: "Sweat Stains", icon: "droplets" },
      { id: "odour", label: "Bad Odour", icon: "wind" },
      { id: "illness", label: "Post-illness Cleaning", icon: "spray" },
      { id: "deep", label: "General Deep Clean", icon: "sparkles" },
      { id: "others", label: "Others", icon: "bed" },
    ],
    defaultIssueId: "deep",
    descriptionPlaceholder: "E.g. Two queen mattresses with sweat stains, family member has dust allergy.",
    photoHint: "Upload photos of the mattress",
  },
  showcaseTitle: "What",
  showcaseHighlight: "We Clean",
  showcaseItems: ["Spring Mattresses", "Foam Mattresses", "Latex Mattresses", "Orthopaedic Mattresses", "Baby Cots", "Pillows", "Mattress Toppers", "Headboards", "PG Beds", "Hotel Beds"],
  showcaseIcon: "bed",
};
